version: '3.2'

services:
  php:
    build: docker/php
    ports:
      - 9000:9000
    volumes:
      - ./app:/app
    depends_on:
      - postgres
      - advisor-go
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./app:/app
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx/
    depends_on:
      - php
  postgres:
    image: postgres:11
    environment:
      - POSTGRES_USER=battleship
      - POSTGRES_PASSWORD=battleship
      - POSTGRES_DB=battleship
    ports:
      - "5433:5432"
    expose:
      - "5432"
  advisor-go:
    build: docker/go
    volumes:
      - ./advisor-go/src/battleship:/go/src/battleship
      - ./advisor-go/test/battleship:/go/test/battleship
    command: go run ./src/battleship/main.go &
    working_dir: /go
    ports:
      - "8383:8383"