version: '3.2'

services:
  php:
    build: docker/php
    ports:
      - 9000:9000
    volumes:
      - .:/app
    depends_on:
      - mysql
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - .:/app
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx/
    depends_on:
      - php
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=battleship
      - MYSQL_USER=battleship
      - MYSQL_PASSWORD=battleship
      - MYSQL_ROOT_PASSWORD=battleship
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql